// user related actions
export const USER_GET_FRIENDS_SUCCESS = 'USER_GET_FRIENDS_SUCCESS';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';

// api status
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

// api calls
export const LOAD_USER_FRIENDS_API_CALL = 'LOAD_USER_FRIENDS_API_CALL';
export const USER_SIGN_IN_API_CALL = 'USER_SIGN_IN_API_CALL';
export const USER_SIGN_OUT_API_CALL = 'USER_SIGN_OUT_API_CALL';
export const USER_SIGN_UP_API_CALL = 'USER_SIGN_UP_API_CALL';
export const USER_UPDATE_PROFILE_API_CALL = 'USER_UPDATE_PROFILE_API_CALL';

// modals
export const SHOW_INVITE_FRIENDS_MODAL = 'SHOW_INVITE_FRIENDS_MODAL';
export const HIDE_INVITE_FRIENDS_MODAL = 'HIDE_INVITE_FRIENDS_MODAL';
