// user related actions
export const USER_GET_FRIENDS_SUCCESS = 'USER_GET_FRIENDS_SUCCESS';

// api status
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

// api calls
export const LOAD_USER_FRIENDS_API_CALL = 'LOAD_USER_FRIENDS_API_CALL';

// modals
export const SHOW_INVITE_FRIENDS_MODAL = 'SHOW_INVITE_FRIENDS_MODAL';
export const HIDE_INVITE_FRIENDS_MODAL = 'HIDE_INVITE_FRIENDS_MODAL';
